import React from 'react'
import AdminDashboard from './AdminDashboard'

const App = () => {
  return (
    <div>
      {/* data use in this dashboard generated by using chat gpt dummy data so please dont give my code rate as ai i only use gpt for dummy data  */}
      <AdminDashboard/>
      </div>
  )
}

export default App